
import { Aleo } from "next/font/google";
import "./globals.css";
import Footer from "../src/Footer/Footer.jsx"; 
import Header from "../src/Header/Header.jsx";




const aleo = Aleo({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={aleo.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
      
    </html>
  );
}

